package no.skatteetaten.fastsetting.formueinntekt.skattemelding.selskapsmelding.sdf.beregning.kalkyler

import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v2_2023.mellomvaerendetype_2023
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v2_2023.transaksjonstype_2023
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v4_2025.beskatningsordningForSkipsaksjeselskapSkipsalmennaksjeselskapMv_2025
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v4_2025.overdragelsestype_2025
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v4_2025.skipsstatusKnyttetTilRederiskatteordning_2025

val skipsstatusKnyttetTilRederiskatteordning = skipsstatusKnyttetTilRederiskatteordning_2025
val overdragelsestype = overdragelsestype_2025
val beskatningsordningForSkipsaksjeselskapSkipsalmennaksjeselskapMv = beskatningsordningForSkipsaksjeselskapSkipsalmennaksjeselskapMv_2025
val transaksjonstype2023 = transaksjonstype_2023
val mellomvaerendetype2023 = mellomvaerendetype_2023
