package no.skatteetaten.fastsetting.formueinntekt.skattemelding.selskapsmelding.sdf.beregning.kalkyler

import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v2_2023.mellomvaerendetype_2023
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v2_2023.transaksjonstype_2023
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v5_2026.beskatningsordningForSkipsaksjeselskapSkipsalmennaksjeselskapMv_2026
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v5_2026.overdragelsestype_2026
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v5_2026.skipsstatusKnyttetTilRederiskatteordning_2026

val skipsstatusKnyttetTilRederiskatteordning = skipsstatusKnyttetTilRederiskatteordning_2026
val overdragelsestype = overdragelsestype_2026
val beskatningsordningForSkipsaksjeselskapSkipsalmennaksjeselskapMv = beskatningsordningForSkipsaksjeselskapSkipsalmennaksjeselskapMv_2026
val transaksjonstype2023 = transaksjonstype_2023
val mellomvaerendetype2023 = mellomvaerendetype_2023
