package no.skatteetaten.fastsetting.formueinntekt.skattemelding.selskapsmelding.sdf.beregning.kalkyler

import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v2_2023.mellomvaerendetype_2023
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v2_2023.transaksjonstype_2023
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v3_2024.beskatningsordningForSkipsaksjeselskapSkipsalmennaksjeselskapMv_2024
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v3_2024.overdragelsestype_2024
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.mapping.selskapsmelding.sdf.domenemodell.v3_2024.skipsstatusKnyttetTilRederiskatteordning_2024

val skipsstatusKnyttetTilRederiskatteordning = skipsstatusKnyttetTilRederiskatteordning_2024
val overdragelsestype = overdragelsestype_2024
val beskatningsordningForSkipsaksjeselskapSkipsalmennaksjeselskapMv = beskatningsordningForSkipsaksjeselskapSkipsalmennaksjeselskapMv_2024
val transaksjonstype2023 = transaksjonstype_2023
val mellomvaerendetype2023 = mellomvaerendetype_2023
