package no.skatteetaten.fastsetting.formueinntekt.skattemelding.naering
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.naering.domene.dsl.FeltKoordinat
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.naering.domene.dsl.FieldDataType
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.naering.domene.dsl.ForekomstTypeSpecification
import no.skatteetaten.fastsetting.formueinntekt.skattemelding.naering.domene.dsl.VerdifeltTypeSpecification

object sumDriftskostnad :  VerdifeltTypeSpecification<sumDriftskostnad>(gruppe= "resultatregnskap.driftskostnad.sumDriftskostnad") {
    val beloep : FeltKoordinat<sumDriftskostnad> = FeltKoordinat("resultatregnskap.driftskostnad.sumDriftskostnad.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumDriftskostnad> = FeltKoordinat("resultatregnskap.driftskostnad.sumDriftskostnad.erOverstyrt")
}
object sumGjeldOgEgenkapitalRegnskapsmessigVerdi :  VerdifeltTypeSpecification<sumGjeldOgEgenkapitalRegnskapsmessigVerdi>(gruppe= "balanse.sumGjeldOgEgenkapitalRegnskapsmessigVerdi") {
    val beloep : FeltKoordinat<sumGjeldOgEgenkapitalRegnskapsmessigVerdi> = FeltKoordinat("balanse.sumGjeldOgEgenkapitalRegnskapsmessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumGjeldOgEgenkapitalRegnskapsmessigVerdi> = FeltKoordinat("balanse.sumGjeldOgEgenkapitalRegnskapsmessigVerdi.erOverstyrt")
}
object sumLangsiktigGjeldSkattemessigVerdi :  VerdifeltTypeSpecification<sumLangsiktigGjeldSkattemessigVerdi>(gruppe= "balanse.gjeldOgEgenkapital.sumLangsiktigGjeldSkattemessigVerdi") {
    val beloep : FeltKoordinat<sumLangsiktigGjeldSkattemessigVerdi> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumLangsiktigGjeldSkattemessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumLangsiktigGjeldSkattemessigVerdi> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumLangsiktigGjeldSkattemessigVerdi.erOverstyrt")
}
object sumEkstraordinaerPost :  VerdifeltTypeSpecification<sumEkstraordinaerPost>(gruppe= "resultatregnskap.sumEkstraordinaerPost") {
    val beloep : FeltKoordinat<sumEkstraordinaerPost> = FeltKoordinat("resultatregnskap.sumEkstraordinaerPost.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumEkstraordinaerPost> = FeltKoordinat("resultatregnskap.sumEkstraordinaerPost.erOverstyrt")
}
object sumDriftsinntekt :  VerdifeltTypeSpecification<sumDriftsinntekt>(gruppe= "resultatregnskap.driftsinntekt.sumDriftsinntekt") {
    val erOverstyrt : FeltKoordinat<sumDriftsinntekt> = FeltKoordinat("resultatregnskap.driftsinntekt.sumDriftsinntekt.erOverstyrt")
    val beloep : FeltKoordinat<sumDriftsinntekt> = FeltKoordinat("resultatregnskap.driftsinntekt.sumDriftsinntekt.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object sumFinanskostnad :  VerdifeltTypeSpecification<sumFinanskostnad>(gruppe= "resultatregnskap.sumFinanskostnad") {
    val beloep : FeltKoordinat<sumFinanskostnad> = FeltKoordinat("resultatregnskap.sumFinanskostnad.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumFinanskostnad> = FeltKoordinat("resultatregnskap.sumFinanskostnad.erOverstyrt")
}
object langsiktigGjeld :  ForekomstTypeSpecification<langsiktigGjeld>("balanse.gjeldOgEgenkapital.langsiktigGjeld") {
    val overfoeresIkkeTilSkattemeldingen : FeltKoordinat<langsiktigGjeld> = FeltKoordinat("balanse.gjeldOgEgenkapital.langsiktigGjeld.overfoeresIkkeTilSkattemeldingen")
    val regnskapsmessigVerdi : FeltKoordinat<langsiktigGjeld> = FeltKoordinat("balanse.gjeldOgEgenkapital.langsiktigGjeld.regnskapsmessigVerdi.beloep" ,"balanse.gjeldOgEgenkapital.langsiktigGjeld.regnskapsmessigVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val skattemessigVerdi : FeltKoordinat<langsiktigGjeld> = FeltKoordinat("balanse.gjeldOgEgenkapital.langsiktigGjeld.skattemessigVerdi.beloep" ,"balanse.gjeldOgEgenkapital.langsiktigGjeld.skattemessigVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val langsiktigGjeldtype : FeltKoordinat<langsiktigGjeld> = FeltKoordinat("balanse.gjeldOgEgenkapital.langsiktigGjeld.langsiktigGjeldtype")
}
object sumEiendelSkattemessigVerdi :  VerdifeltTypeSpecification<sumEiendelSkattemessigVerdi>(gruppe= "balanse.sumEiendelSkattemessigVerdi") {
    val beloep : FeltKoordinat<sumEiendelSkattemessigVerdi> = FeltKoordinat("balanse.sumEiendelSkattemessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumEiendelSkattemessigVerdi> = FeltKoordinat("balanse.sumEiendelSkattemessigVerdi.erOverstyrt")
}
object sumAnleggsmiddelSkattemessigVerdi :  VerdifeltTypeSpecification<sumAnleggsmiddelSkattemessigVerdi>(gruppe= "balanse.anleggsmiddel.sumAnleggsmiddelSkattemessigVerdi") {
    val beloep : FeltKoordinat<sumAnleggsmiddelSkattemessigVerdi> = FeltKoordinat("balanse.anleggsmiddel.sumAnleggsmiddelSkattemessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumAnleggsmiddelSkattemessigVerdi> = FeltKoordinat("balanse.anleggsmiddel.sumAnleggsmiddelSkattemessigVerdi.erOverstyrt")
}
object aarsresultat :  VerdifeltTypeSpecification<aarsresultat>(gruppe= "resultatregnskap.aarsresultat") {
    val erOverstyrt : FeltKoordinat<aarsresultat> = FeltKoordinat("resultatregnskap.aarsresultat.erOverstyrt")
    val beloep : FeltKoordinat<aarsresultat> = FeltKoordinat("resultatregnskap.aarsresultat.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object ikkeAvskrivbartAnleggsmiddel :  ForekomstTypeSpecification<ikkeAvskrivbartAnleggsmiddel>("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel") {
    val offentligTilskudd : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.offentligTilskudd.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.offentligTilskudd", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val gevinstOverfoertTilGevinstOgTapskonto : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.gevinstOverfoertTilGevinstOgTapskonto.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.gevinstOverfoertTilGevinstOgTapskonto", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erstatningsbeloepVedUfrivilligRealisasjon : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.erstatningsbeloepVedUfrivilligRealisasjon.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.erstatningsbeloepVedUfrivilligRealisasjon", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val vederlagVedRealisasjonOgUttakInntektsfoertIAar : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.vederlagVedRealisasjonOgUttakInntektsfoertIAar.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.vederlagVedRealisasjonOgUttakInntektsfoertIAar", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val justeringAvInngaaendeMva : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.justeringAvInngaaendeMva.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.justeringAvInngaaendeMva", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val inngaaendeVerdi : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.inngaaendeVerdi.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.inngaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val paakostning : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.paakostning.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.paakostning", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val tapOverfoertTilGevinstOgTapskonto : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.tapOverfoertTilGevinstOgTapskonto.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.tapOverfoertTilGevinstOgTapskonto", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val grunnlagForAvskrivningOgInntektsfoering : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.grunnlagForAvskrivningOgInntektsfoering.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.grunnlagForAvskrivningOgInntektsfoering", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erRealisasjonenUfrivilligOgGevinstenBetingetSkattefri : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.erRealisasjonenUfrivilligOgGevinstenBetingetSkattefri")
    object naeringsfordeling :  ForekomstTypeSpecification<naeringsfordeling>("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel","spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling") {
        val erGevinstenFraRealisasjonAvAlminneligGaardsbrukEllerSkogbruk : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling.gevinstOgTap.erGevinstenFraRealisasjonAvAlminneligGaardsbrukEllerSkogbruk")
        val kommunenummer : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling.kommunenummer")
        val andelBenyttetINaeringen : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling.andelBenyttetINaeringen")
        val gevinstOgTapskontoIdentifikator : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling.gevinstOgTap.gevinstOgTapskontoIdentifikator")
        val tapVedRealisasjonOgUttak : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling.gevinstOgTap.tapVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling.gevinstOgTap.tapVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
        val gevinstVedRealisasjonOgUttak : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling.gevinstOgTap.gevinstVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling.gevinstOgTap.gevinstVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
        val naeringsidentifikator : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.naeringsfordeling.naeringsidentifikator")
    }
    val nedskrivningPaaNyanskaffelserMedBetingetSkattefriSalgsgevinst : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.nedskrivningPaaNyanskaffelserMedBetingetSkattefriSalgsgevinst.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.nedskrivningPaaNyanskaffelserMedBetingetSkattefriSalgsgevinst", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val utgaaendeVerdi : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.utgaaendeVerdi.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.utgaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val tilbakefoeringAvTilskuddTilInvesteringIDistriktene : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.tilbakefoeringAvTilskuddTilInvesteringIDistriktene.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.tilbakefoeringAvTilskuddTilInvesteringIDistriktene", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val nyanskaffelse : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.nyanskaffelse.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.nyanskaffelse", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val vederlagVedRealisasjonOgUttak : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.vederlagVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.vederlagVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val justeringForAapenbarVerdiendring : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.justeringForAapenbarVerdiendring.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.justeringForAapenbarVerdiendring", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val objektbeskrivelse : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.objektbeskrivelse")
    val objektidentifikator : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.objektidentifikator")
    val ervervsdato : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.ervervsdato")
    val objektidentifikatorNedskrivningenMedBetingetSkattefriSalgsgevinstGjelder : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.objektidentifikatorNedskrivningenMedBetingetSkattefriSalgsgevinstGjelder")
    val tilskuddTilInvesteringIDistriktene : FeltKoordinat<ikkeAvskrivbartAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.tilskuddTilInvesteringIDistriktene.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.ikkeAvskrivbartAnleggsmiddel.tilskuddTilInvesteringIDistriktene", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object finansinntekter :  ForekomstTypeSpecification<finansinntekter>("resultatregnskap.finansinntekter") {
    object finansinntekt :  ForekomstTypeSpecification<finansinntekt>("resultatregnskap.finansinntekter","resultatregnskap.finansinntekter.finansinntekt") {
        val type : FeltKoordinat<finansinntekt> = FeltKoordinat("resultatregnskap.finansinntekter.finansinntekt.type")
        val beloep : FeltKoordinat<finansinntekt> = FeltKoordinat("resultatregnskap.finansinntekter.finansinntekt.beloep.beloep" ,"resultatregnskap.finansinntekter.finansinntekt.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
}
object sumKortsiktigGjeldRegnskapsmessigVerdi :  VerdifeltTypeSpecification<sumKortsiktigGjeldRegnskapsmessigVerdi>(gruppe= "balanse.gjeldOgEgenkapital.sumKortsiktigGjeldRegnskapsmessigVerdi") {
    val beloep : FeltKoordinat<sumKortsiktigGjeldRegnskapsmessigVerdi> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumKortsiktigGjeldRegnskapsmessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumKortsiktigGjeldRegnskapsmessigVerdi> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumKortsiktigGjeldRegnskapsmessigVerdi.erOverstyrt")
}
object sumAnleggsmiddelRegnskapsmessigVerdi :  VerdifeltTypeSpecification<sumAnleggsmiddelRegnskapsmessigVerdi>(gruppe= "balanse.anleggsmiddel.sumAnleggsmiddelRegnskapsmessigVerdi") {
    val erOverstyrt : FeltKoordinat<sumAnleggsmiddelRegnskapsmessigVerdi> = FeltKoordinat("balanse.anleggsmiddel.sumAnleggsmiddelRegnskapsmessigVerdi.erOverstyrt")
    val beloep : FeltKoordinat<sumAnleggsmiddelRegnskapsmessigVerdi> = FeltKoordinat("balanse.anleggsmiddel.sumAnleggsmiddelRegnskapsmessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object sumEiendelRegnskapsmessigVerdi :  VerdifeltTypeSpecification<sumEiendelRegnskapsmessigVerdi>(gruppe= "balanse.sumEiendelRegnskapsmessigVerdi") {
    val beloep : FeltKoordinat<sumEiendelRegnskapsmessigVerdi> = FeltKoordinat("balanse.sumEiendelRegnskapsmessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumEiendelRegnskapsmessigVerdi> = FeltKoordinat("balanse.sumEiendelRegnskapsmessigVerdi.erOverstyrt")
}
object sumSkattekostnad :  VerdifeltTypeSpecification<sumSkattekostnad>(gruppe= "resultatregnskap.sumSkattekostnad") {
    val beloep : FeltKoordinat<sumSkattekostnad> = FeltKoordinat("resultatregnskap.sumSkattekostnad.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumSkattekostnad> = FeltKoordinat("resultatregnskap.sumSkattekostnad.erOverstyrt")
}
object ekstraordinaerePoster :  ForekomstTypeSpecification<ekstraordinaerePoster>("resultatregnskap.ekstraordinaerePoster") {
    object ekstraordinaerPost :  ForekomstTypeSpecification<ekstraordinaerPost>("resultatregnskap.ekstraordinaerePoster","resultatregnskap.ekstraordinaerePoster.ekstraordinaerPost") {
        val kostnad : FeltKoordinat<ekstraordinaerPost> = FeltKoordinat("resultatregnskap.ekstraordinaerePoster.ekstraordinaerPost.kostnad.beloep" ,"resultatregnskap.ekstraordinaerePoster.ekstraordinaerPost.kostnad", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
        val inntekt : FeltKoordinat<ekstraordinaerPost> = FeltKoordinat("resultatregnskap.ekstraordinaerePoster.ekstraordinaerPost.inntekt.beloep" ,"resultatregnskap.ekstraordinaerePoster.ekstraordinaerPost.inntekt", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
}
object loennskostnader :  ForekomstTypeSpecification<loennskostnader>("resultatregnskap.driftskostnad.loennskostnader") {
    object loennskostnad :  ForekomstTypeSpecification<loennskostnad>("resultatregnskap.driftskostnad.loennskostnader","resultatregnskap.driftskostnad.loennskostnader.loennskostnad") {
        val type : FeltKoordinat<loennskostnad> = FeltKoordinat("resultatregnskap.driftskostnad.loennskostnader.loennskostnad.type")
        val beloep : FeltKoordinat<loennskostnad> = FeltKoordinat("resultatregnskap.driftskostnad.loennskostnader.loennskostnad.beloep.beloep" ,"resultatregnskap.driftskostnad.loennskostnader.loennskostnad.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
}
object skattekostnader :  ForekomstTypeSpecification<skattekostnader>("resultatregnskap.skattekostnader") {
    object skattekostnad :  ForekomstTypeSpecification<skattekostnad>("resultatregnskap.skattekostnader","resultatregnskap.skattekostnader.skattekostnad") {
        val skattekostnad : FeltKoordinat<skattekostnad> = FeltKoordinat("resultatregnskap.skattekostnader.skattekostnad.skattekostnad.beloep" ,"resultatregnskap.skattekostnader.skattekostnad.skattekostnad", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
        val type : FeltKoordinat<skattekostnad> = FeltKoordinat("resultatregnskap.skattekostnader.skattekostnad.type")
        val negativSkattekostnad : FeltKoordinat<skattekostnad> = FeltKoordinat("resultatregnskap.skattekostnader.skattekostnad.negativSkattekostnad.beloep" ,"resultatregnskap.skattekostnader.skattekostnad.negativSkattekostnad", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
}
object personinntektFraEnkeltpersonforetak :  ForekomstTypeSpecification<personinntektFraEnkeltpersonforetak>("personinntektFraEnkeltpersonforetak") {
    val skjermingsfradrag : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.skjermingsfradrag.beloep" ,"personinntektFraEnkeltpersonforetak.skjermingsfradrag", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    object spesifikasjonAvSkjermingsgrunnlag :  ForekomstTypeSpecification<spesifikasjonAvSkjermingsgrunnlag>("personinntektFraEnkeltpersonforetak","personinntektFraEnkeltpersonforetak.spesifikasjonAvSkjermingsgrunnlag") {
        val inngaaendeVerdi : FeltKoordinat<spesifikasjonAvSkjermingsgrunnlag> = FeltKoordinat("personinntektFraEnkeltpersonforetak.spesifikasjonAvSkjermingsgrunnlag.inngaaendeVerdi.beloep" ,"personinntektFraEnkeltpersonforetak.spesifikasjonAvSkjermingsgrunnlag.inngaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
        val skjermingsgrunnlagstype : FeltKoordinat<spesifikasjonAvSkjermingsgrunnlag> = FeltKoordinat("personinntektFraEnkeltpersonforetak.spesifikasjonAvSkjermingsgrunnlag.skjermingsgrunnlagstype")
        val utgaaendeVerdi : FeltKoordinat<spesifikasjonAvSkjermingsgrunnlag> = FeltKoordinat("personinntektFraEnkeltpersonforetak.spesifikasjonAvSkjermingsgrunnlag.utgaaendeVerdi.beloep" ,"personinntektFraEnkeltpersonforetak.spesifikasjonAvSkjermingsgrunnlag.utgaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
    val identifikatorForFordelingAvNaeringsinntektOgPersoninntekt : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.identifikatorForFordelingAvNaeringsinntektOgPersoninntekt")
    val kapitalinntekt : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.kapitalinntekt.beloep" ,"personinntektFraEnkeltpersonforetak.kapitalinntekt", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val reduksjonsbeloepForLeidEiendomMotInnskudd : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.reduksjonsbeloepForLeidEiendomMotInnskudd.beloep" ,"personinntektFraEnkeltpersonforetak.reduksjonsbeloepForLeidEiendomMotInnskudd", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val sumSkjermingsgrunnlagEtterGjeldsfradrag : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.sumSkjermingsgrunnlagEtterGjeldsfradrag.beloep" ,"personinntektFraEnkeltpersonforetak.sumSkjermingsgrunnlagEtterGjeldsfradrag", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val skjermingsrente : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.skjermingsrente")
    val sumSkjermingsgrunnlagFoerGjeldsfradrag : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.sumSkjermingsgrunnlagFoerGjeldsfradrag.beloep" ,"personinntektFraEnkeltpersonforetak.sumSkjermingsgrunnlagFoerGjeldsfradrag", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val rentekostnadPaaForetaksgjeld : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.rentekostnadPaaForetaksgjeld.beloep" ,"personinntektFraEnkeltpersonforetak.rentekostnadPaaForetaksgjeld", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val kapitalkostnad : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.kapitalkostnad.beloep" ,"personinntektFraEnkeltpersonforetak.kapitalkostnad", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val aaretsBeregnedePersoninntektFoerFordelingOgSamordning : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.aaretsBeregnedePersoninntektFoerFordelingOgSamordning.beloep" ,"personinntektFraEnkeltpersonforetak.aaretsBeregnedePersoninntektFoerFordelingOgSamordning", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val gevinstVedRealisasjonAvAlminneligGaardsbrukEllerSkogbruk : FeltKoordinat<personinntektFraEnkeltpersonforetak> = FeltKoordinat("personinntektFraEnkeltpersonforetak.gevinstVedRealisasjonAvAlminneligGaardsbrukEllerSkogbruk.beloep" ,"personinntektFraEnkeltpersonforetak.gevinstVedRealisasjonAvAlminneligGaardsbrukEllerSkogbruk", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object egenkapital :  ForekomstTypeSpecification<egenkapital>("balanse.gjeldOgEgenkapital.egenkapital") {
    val egenkapitaltype : FeltKoordinat<egenkapital> = FeltKoordinat("balanse.gjeldOgEgenkapital.egenkapital.egenkapitaltype")
    val beloep : FeltKoordinat<egenkapital> = FeltKoordinat("balanse.gjeldOgEgenkapital.egenkapital.beloep.beloep" ,"balanse.gjeldOgEgenkapital.egenkapital.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object lineaertavskrevetAnleggsmiddel :  ForekomstTypeSpecification<lineaertavskrevetAnleggsmiddel>("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel") {
    val ervervsdato : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.ervervsdato")
    val tilbakefoeringAvTilskuddTilInvesteringIDistriktene : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.tilbakefoeringAvTilskuddTilInvesteringIDistriktene.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.tilbakefoeringAvTilskuddTilInvesteringIDistriktene", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val tapOverfoertTilGevinstOgTapskonto : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.tapOverfoertTilGevinstOgTapskonto.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.tapOverfoertTilGevinstOgTapskonto", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val verdiOverfoertTilDriftsmiddelVedRealisasjon : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.verdiOverfoertTilDriftsmiddelVedRealisasjon.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.verdiOverfoertTilDriftsmiddelVedRealisasjon", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erRealisasjonenUfrivilligOgGevinstenBetingetSkattefri : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.erRealisasjonenUfrivilligOgGevinstenBetingetSkattefri")
    val paakostning : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.paakostning.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.paakostning", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val anskaffelseskost : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.anskaffelseskost.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.anskaffelseskost", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erstatningsbeloepVedUfrivilligRealisasjon : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.erstatningsbeloepVedUfrivilligRealisasjon.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.erstatningsbeloepVedUfrivilligRealisasjon", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val realisasjonsdato : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.realisasjonsdato")
    val vederlagVedRealisasjonOgUttak : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.vederlagVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.vederlagVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val verdiOverfoertFraPaakostningVedRealisasjon : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.verdiOverfoertFraPaakostningVedRealisasjon.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.verdiOverfoertFraPaakostningVedRealisasjon", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    object naeringsfordeling :  ForekomstTypeSpecification<naeringsfordeling>("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel","spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling") {
        val erGevinstenFraRealisasjonAvAlminneligGaardsbrukEllerSkogbruk : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.erGevinstenFraRealisasjonAvAlminneligGaardsbrukEllerSkogbruk")
        val andelBenyttetINaeringen : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling.andelBenyttetINaeringen")
        val kommunenummer : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling.kommunenummer")
        val tapVedRealisasjonOgUttak : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.tapVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.tapVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
        val gevinstOgTapskontoIdentifikator : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.gevinstOgTapskontoIdentifikator")
        val naeringsidentifikator : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling.naeringsidentifikator")
        val gevinstVedRealisasjonOgUttak : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.gevinstVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.gevinstVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
    val objektbeskrivelse : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.objektbeskrivelse")
    val justeringForAapenbarVerdiendring : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.justeringForAapenbarVerdiendring.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.justeringForAapenbarVerdiendring", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val utgaaendeVerdi : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.utgaaendeVerdi.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.utgaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val justeringAvInngaaendeMva : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.justeringAvInngaaendeMva.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.justeringAvInngaaendeMva", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val objektidentifikatorNedskrivningenMedBetingetSkattefriSalgsgevinstGjelder : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.objektidentifikatorNedskrivningenMedBetingetSkattefriSalgsgevinstGjelder")
    val objektidentifikator : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.objektidentifikator")
    val grunnlagForAvskrivningOgInntektsfoering : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.grunnlagForAvskrivningOgInntektsfoering.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.grunnlagForAvskrivningOgInntektsfoering", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val inngaaendeVerdi : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.inngaaendeVerdi.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.inngaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val tilskuddTilInvesteringIDistriktene : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.tilskuddTilInvesteringIDistriktene.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.tilskuddTilInvesteringIDistriktene", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val levetid : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.levetid")
    val aaretsAvskrivning : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.aaretsAvskrivning.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.aaretsAvskrivning", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val nedskrivningPaaNyanskaffelserMedBetingetSkattefriSalgsgevinst : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.nedskrivningPaaNyanskaffelserMedBetingetSkattefriSalgsgevinst.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.nedskrivningPaaNyanskaffelserMedBetingetSkattefriSalgsgevinst", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val offentligTilskudd : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.offentligTilskudd.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.offentligTilskudd", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val gevinstOverfoertTilGevinstOgTapskonto : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.gevinstOverfoertTilGevinstOgTapskonto.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.gevinstOverfoertTilGevinstOgTapskonto", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val vederlagVedRealisasjonOgUttakInntektsfoertIAar : FeltKoordinat<lineaertavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.vederlagVedRealisasjonOgUttakInntektsfoertIAar.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.lineaertavskrevetAnleggsmiddel.vederlagVedRealisasjonOgUttakInntektsfoertIAar", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object fordelingAvNaeringsinntekt :  ForekomstTypeSpecification<fordelingAvNaeringsinntekt>("fordelingAvNaeringsinntekt") {
    val resultatIFjor : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.resultatIFjor.beloep" ,"fordelingAvNaeringsinntekt.reindrift.resultatIFjor", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val korrigertResultat : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.korrigertResultat.beloep" ,"fordelingAvNaeringsinntekt.reindrift.korrigertResultat", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val sjablongberegnetInntektFraBiomasseVedproduksjon : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.sjablongberegnetInntektFraBiomasseVedproduksjon.beloep" ,"fordelingAvNaeringsinntekt.sjablongberegnetInntektFraBiomasseVedproduksjon", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val korreksjonForEndringIAvviklingsOgOmstillingsfondForReineiere : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.korreksjonForEndringIAvviklingsOgOmstillingsfondForReineiere.beloep" ,"fordelingAvNaeringsinntekt.reindrift.korreksjonForEndringIAvviklingsOgOmstillingsfondForReineiere", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val resultatForToAarSiden : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.resultatForToAarSiden.beloep" ,"fordelingAvNaeringsinntekt.reindrift.resultatForToAarSiden", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val korrigeringForBeloepFraGevinstOgTapskonto : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.korrigeringForBeloepFraGevinstOgTapskonto.beloep" ,"fordelingAvNaeringsinntekt.reindrift.korrigeringForBeloepFraGevinstOgTapskonto", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val grunnlagForBeregningAvReindriftsfradrag : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.grunnlagForBeregningAvReindriftsfradrag.beloep" ,"fordelingAvNaeringsinntekt.reindrift.grunnlagForBeregningAvReindriftsfradrag", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val uttakFraAvviklingsOgOmstillingsfondForReineiere : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.uttakFraAvviklingsOgOmstillingsfondForReineiere.beloep" ,"fordelingAvNaeringsinntekt.reindrift.uttakFraAvviklingsOgOmstillingsfondForReineiere", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val identifikatorForFordelingAvNaeringsinntektOgPersoninntekt : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.identifikatorForFordelingAvNaeringsinntektOgPersoninntekt")
    val naeringsbeskrivelse : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.naeringsbeskrivelse")
    val korreksjonForDifferanseMellomKorrigertResultatOgGjennomsnittsinntekt : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.korreksjonForDifferanseMellomKorrigertResultatOgGjennomsnittsinntekt.beloep" ,"fordelingAvNaeringsinntekt.reindrift.korreksjonForDifferanseMellomKorrigertResultatOgGjennomsnittsinntekt", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val skattemessigResultatForNaering : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.skattemessigResultatForNaering.beloep" ,"fordelingAvNaeringsinntekt.skattemessigResultatForNaering", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val andelAvSkattemessigResultatTilordnetInnehaver : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.andelAvSkattemessigResultatTilordnetInnehaver")
    val korreksjonFraReindrift : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.korreksjonFraReindrift.beloep" ,"fordelingAvNaeringsinntekt.korreksjonFraReindrift", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val innskuddIAvviklingsOgOmstillingsfondForReineiere : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.innskuddIAvviklingsOgOmstillingsfondForReineiere.beloep" ,"fordelingAvNaeringsinntekt.reindrift.innskuddIAvviklingsOgOmstillingsfondForReineiere", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val gjennomsnittsinntekt : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.gjennomsnittsinntekt.beloep" ,"fordelingAvNaeringsinntekt.reindrift.gjennomsnittsinntekt", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val skattemessigResultatForNaeringEtterKorreksjonTilordnetInnehaver : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.skattemessigResultatForNaeringEtterKorreksjonTilordnetInnehaver.beloep" ,"fordelingAvNaeringsinntekt.skattemessigResultatForNaeringEtterKorreksjonTilordnetInnehaver", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val korrigeringForKapitalInntektOgKapitalkostnad : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.reindrift.korrigeringForKapitalInntektOgKapitalkostnad.beloep" ,"fordelingAvNaeringsinntekt.reindrift.korrigeringForKapitalInntektOgKapitalkostnad", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val naeringstype : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.naeringstype")
    val skattemessigResultatForNaeringEtterKorreksjon : FeltKoordinat<fordelingAvNaeringsinntekt> = FeltKoordinat("fordelingAvNaeringsinntekt.skattemessigResultatForNaeringEtterKorreksjon.beloep" ,"fordelingAvNaeringsinntekt.skattemessigResultatForNaeringEtterKorreksjon", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object andreDriftsinntekter :  ForekomstTypeSpecification<andreDriftsinntekter>("resultatregnskap.driftsinntekt.andreDriftsinntekter") {
    object annenDriftsinntekt :  ForekomstTypeSpecification<annenDriftsinntekt>("resultatregnskap.driftsinntekt.andreDriftsinntekter","resultatregnskap.driftsinntekt.andreDriftsinntekter.annenDriftsinntekt") {
        val type : FeltKoordinat<annenDriftsinntekt> = FeltKoordinat("resultatregnskap.driftsinntekt.andreDriftsinntekter.annenDriftsinntekt.type")
        val beloep : FeltKoordinat<annenDriftsinntekt> = FeltKoordinat("resultatregnskap.driftsinntekt.andreDriftsinntekter.annenDriftsinntekt.beloep.beloep" ,"resultatregnskap.driftsinntekt.andreDriftsinntekter.annenDriftsinntekt.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
}
object gevinstOgTapskonto :  ForekomstTypeSpecification<gevinstOgTapskonto>("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto") {
    val inntektFraGevinstOgTapskonto : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.inntektFraGevinstOgTapskonto.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.inntektFraGevinstOgTapskonto", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val gevinstOgTapskontoIdentifikator : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.gevinstOgTapskontoIdentifikator")
    val kommunenummer : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.kommunenummer")
    val naeringsidentifikator : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.naeringsidentifikator")
    val inntektsfradragFraGevinstOgTapskonto : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.inntektsfradragFraGevinstOgTapskonto.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.inntektsfradragFraGevinstOgTapskonto", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val inngaaendeVerdi : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.inngaaendeVerdi.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.inngaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val sumTapVedRealisasjonOgUttak : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.sumTapVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.sumTapVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val utgaaendeVerdi : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.utgaaendeVerdi.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.utgaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val grunnlagForAaretsInntektsOgFradragsfoering : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.grunnlagForAaretsInntektsOgFradragsfoering.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.grunnlagForAaretsInntektsOgFradragsfoering", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val stammerGevinstOgTapskontoenFraRealisasjonAvTomtFraAlminneligJordbrukEllerSkogbruk : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.stammerGevinstOgTapskontoenFraRealisasjonAvTomtFraAlminneligJordbrukEllerSkogbruk")
    val sumGevinstVedRealisasjonOgUttak : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.sumGevinstVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.sumGevinstVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val satsForInntektsfoeringOgInntektsfradrag : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.satsForInntektsfoeringOgInntektsfradrag")
    val gevinstVedRealisasjonAvHelBuskapPaaGaardsbrukVedOpphoerAvDriftsgren : FeltKoordinat<gevinstOgTapskonto> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.gevinstVedRealisasjonAvHelBuskapPaaGaardsbrukVedOpphoerAvDriftsgren.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.gevinstOgTapskonto.gevinstVedRealisasjonAvHelBuskapPaaGaardsbrukVedOpphoerAvDriftsgren", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object sumEgenkapital :  VerdifeltTypeSpecification<sumEgenkapital>(gruppe= "balanse.gjeldOgEgenkapital.sumEgenkapital") {
    val beloep : FeltKoordinat<sumEgenkapital> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumEgenkapital.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumEgenkapital> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumEgenkapital.erOverstyrt")
}
object sumResultatkomponentForIFRSForetak :  VerdifeltTypeSpecification<sumResultatkomponentForIFRSForetak>(gruppe= "resultatregnskap.sumResultatkomponentForIFRSForetak") {
    val erOverstyrt : FeltKoordinat<sumResultatkomponentForIFRSForetak> = FeltKoordinat("resultatregnskap.sumResultatkomponentForIFRSForetak.erOverstyrt")
    val beloep : FeltKoordinat<sumResultatkomponentForIFRSForetak> = FeltKoordinat("resultatregnskap.sumResultatkomponentForIFRSForetak.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object salgsinntekter :  ForekomstTypeSpecification<salgsinntekter>("resultatregnskap.driftsinntekt.salgsinntekter") {
    object salgsinntekt :  ForekomstTypeSpecification<salgsinntekt>("resultatregnskap.driftsinntekt.salgsinntekter","resultatregnskap.driftsinntekt.salgsinntekter.salgsinntekt") {
        val type : FeltKoordinat<salgsinntekt> = FeltKoordinat("resultatregnskap.driftsinntekt.salgsinntekter.salgsinntekt.type")
        val beloep : FeltKoordinat<salgsinntekt> = FeltKoordinat("resultatregnskap.driftsinntekt.salgsinntekter.salgsinntekt.beloep.beloep" ,"resultatregnskap.driftsinntekt.salgsinntekter.salgsinntekt.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
}
object balanseverdiForOmloepsmiddel :  ForekomstTypeSpecification<balanseverdiForOmloepsmiddel>("balanse.omloepsmiddel.balanseverdiForOmloepsmiddel") {
    val overfoeresIkkeTilSkattemeldingen : FeltKoordinat<balanseverdiForOmloepsmiddel> = FeltKoordinat("balanse.omloepsmiddel.balanseverdiForOmloepsmiddel.overfoeresIkkeTilSkattemeldingen")
    val regnskapsmessigVerdi : FeltKoordinat<balanseverdiForOmloepsmiddel> = FeltKoordinat("balanse.omloepsmiddel.balanseverdiForOmloepsmiddel.regnskapsmessigVerdi.beloep" ,"balanse.omloepsmiddel.balanseverdiForOmloepsmiddel.regnskapsmessigVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val skattemessigVerdi : FeltKoordinat<balanseverdiForOmloepsmiddel> = FeltKoordinat("balanse.omloepsmiddel.balanseverdiForOmloepsmiddel.skattemessigVerdi.beloep" ,"balanse.omloepsmiddel.balanseverdiForOmloepsmiddel.skattemessigVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val omloepsmiddeltype : FeltKoordinat<balanseverdiForOmloepsmiddel> = FeltKoordinat("balanse.omloepsmiddel.balanseverdiForOmloepsmiddel.omloepsmiddeltype")
}
object saldoavskrevetAnleggsmiddel :  ForekomstTypeSpecification<saldoavskrevetAnleggsmiddel>("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel") {
    val avskrivningssats : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.avskrivningssats")
    val utgaaendeVerdi : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.utgaaendeVerdi.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.utgaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val nyanskaffelse : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.nyanskaffelse.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.nyanskaffelse", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val nedreGrenseForAvskrivning : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.forretningsbyggAnskaffetFoer01011984.nedreGrenseForAvskrivning.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.forretningsbyggAnskaffetFoer01011984.nedreGrenseForAvskrivning", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erstatningsbeloepVedUfrivilligRealisasjon : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.erstatningsbeloepVedUfrivilligRealisasjon.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.erstatningsbeloepVedUfrivilligRealisasjon", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val saldogruppe : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.saldogruppe")
    val justeringAvInngaaendeMva : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.justeringAvInngaaendeMva.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.justeringAvInngaaendeMva", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val grunnlagForAvskrivningOgInntektsfoering : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.grunnlagForAvskrivningOgInntektsfoering.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.grunnlagForAvskrivningOgInntektsfoering", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val nedskrevetVerdiPr01011984 : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.forretningsbyggAnskaffetFoer01011984.nedskrevetVerdiPr01011984.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.forretningsbyggAnskaffetFoer01011984.nedskrevetVerdiPr01011984", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val grunnlagForStartavskrivning : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.grunnlagForStartavskrivning.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.grunnlagForStartavskrivning", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    object naeringsfordeling :  ForekomstTypeSpecification<naeringsfordeling>("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel","spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling") {
        val gevinstVedRealisasjonOgUttak : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.gevinstVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.gevinstVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
        val erGevinstenFraRealisasjonAvAlminneligGaardsbrukEllerSkogbruk : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.erGevinstenFraRealisasjonAvAlminneligGaardsbrukEllerSkogbruk")
        val gevinstOgTapskontoIdentifikator : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.gevinstOgTapskontoIdentifikator")
        val tapVedRealisasjonOgUttak : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.tapVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling.gevinstOgTap.tapVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
        val naeringsidentifikator : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling.naeringsidentifikator")
        val andelBenyttetINaeringen : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling.andelBenyttetINaeringen")
        val kommunenummer : FeltKoordinat<naeringsfordeling> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.naeringsfordeling.kommunenummer")
    }
    val objektidentifikator : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.objektidentifikator")
    val gevinstOverfoertTilGevinstOgTapskonto : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.gevinstOverfoertTilGevinstOgTapskonto.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.gevinstOverfoertTilGevinstOgTapskonto", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val paakostning : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.paakostning.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.paakostning", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val offentligTilskudd : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.offentligTilskudd.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.offentligTilskudd", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val tilskuddTilInvesteringIDistriktene : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.tilskuddTilInvesteringIDistriktene.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.tilskuddTilInvesteringIDistriktene", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val vederlagVedRealisasjonOgUttakInntektsfoertIAar : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.vederlagVedRealisasjonOgUttakInntektsfoertIAar.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.vederlagVedRealisasjonOgUttakInntektsfoertIAar", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erDetFysiskeDriftsmidlerIUtgaaendeVerdi : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.erDetFysiskeDriftsmidlerIUtgaaendeVerdi")
    val tilbakefoeringAvTilskuddTilInvesteringIDistriktene : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.tilbakefoeringAvTilskuddTilInvesteringIDistriktene.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.tilbakefoeringAvTilskuddTilInvesteringIDistriktene", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val aaretsInntektsfoeringAvNegativSaldo : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.aaretsInntektsfoeringAvNegativSaldo.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.aaretsInntektsfoeringAvNegativSaldo", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val ervervsdato : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.ervervsdato")
    val aaretsAvskrivning : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.aaretsAvskrivning.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.aaretsAvskrivning", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val vederlagVedRealisasjonOgUttak : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.vederlagVedRealisasjonOgUttak.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.vederlagVedRealisasjonOgUttak", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val objektidentifikatorNedskrivningenMedBetingetSkattefriSalgsgevinstGjelder : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.objektidentifikatorNedskrivningenMedBetingetSkattefriSalgsgevinstGjelder")
    val historiskKostpris : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.forretningsbyggAnskaffetFoer01011984.historiskKostpris.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.forretningsbyggAnskaffetFoer01011984.historiskKostpris", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val nedskrivningPaaNyanskaffelserMedBetingetSkattefriSalgsgevinst : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.nedskrivningPaaNyanskaffelserMedBetingetSkattefriSalgsgevinst.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.nedskrivningPaaNyanskaffelserMedBetingetSkattefriSalgsgevinst", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val tapOverfoertTilGevinstOgTapskonto : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.tapOverfoertTilGevinstOgTapskonto.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.tapOverfoertTilGevinstOgTapskonto", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val objektbeskrivelse : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.objektbeskrivelse")
    val nedskrevetVerdiAvUtskilteDriftsmidler : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.nedskrevetVerdiAvUtskilteDriftsmidler.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.nedskrevetVerdiAvUtskilteDriftsmidler", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val inngaaendeVerdi : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.inngaaendeVerdi.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.inngaaendeVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erRealisasjonenUfrivilligOgGevinstenBetingetSkattefri : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.erRealisasjonenUfrivilligOgGevinstenBetingetSkattefri")
    val avskrivningssatsForStartavskrivning : FeltKoordinat<saldoavskrevetAnleggsmiddel> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.saldoavskrevetAnleggsmiddel.avskrivningssatsForStartavskrivning")
}
object finanskostnader :  ForekomstTypeSpecification<finanskostnader>("resultatregnskap.finanskostnader") {
    object finanskostnad :  ForekomstTypeSpecification<finanskostnad>("resultatregnskap.finanskostnader","resultatregnskap.finanskostnader.finanskostnad") {
        val type : FeltKoordinat<finanskostnad> = FeltKoordinat("resultatregnskap.finanskostnader.finanskostnad.type")
        val beloep : FeltKoordinat<finanskostnad> = FeltKoordinat("resultatregnskap.finanskostnader.finanskostnad.beloep.beloep" ,"resultatregnskap.finanskostnader.finanskostnad.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
}
object sumOmloepsmiddelSkattemessigVerdi :  VerdifeltTypeSpecification<sumOmloepsmiddelSkattemessigVerdi>(gruppe= "balanse.omloepsmiddel.sumOmloepsmiddelSkattemessigVerdi") {
    val erOverstyrt : FeltKoordinat<sumOmloepsmiddelSkattemessigVerdi> = FeltKoordinat("balanse.omloepsmiddel.sumOmloepsmiddelSkattemessigVerdi.erOverstyrt")
    val beloep : FeltKoordinat<sumOmloepsmiddelSkattemessigVerdi> = FeltKoordinat("balanse.omloepsmiddel.sumOmloepsmiddelSkattemessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object balanseverdiForAnleggsmiddel :  ForekomstTypeSpecification<balanseverdiForAnleggsmiddel>("balanse.anleggsmiddel.balanseverdiForAnleggsmiddel") {
    val anleggsmiddeltype : FeltKoordinat<balanseverdiForAnleggsmiddel> = FeltKoordinat("balanse.anleggsmiddel.balanseverdiForAnleggsmiddel.anleggsmiddeltype")
    val regnskapsmessigVerdi : FeltKoordinat<balanseverdiForAnleggsmiddel> = FeltKoordinat("balanse.anleggsmiddel.balanseverdiForAnleggsmiddel.regnskapsmessigVerdi.beloep" ,"balanse.anleggsmiddel.balanseverdiForAnleggsmiddel.regnskapsmessigVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val overfoeresIkkeTilSkattemeldingen : FeltKoordinat<balanseverdiForAnleggsmiddel> = FeltKoordinat("balanse.anleggsmiddel.balanseverdiForAnleggsmiddel.overfoeresIkkeTilSkattemeldingen")
    val skattemessigVerdi : FeltKoordinat<balanseverdiForAnleggsmiddel> = FeltKoordinat("balanse.anleggsmiddel.balanseverdiForAnleggsmiddel.skattemessigVerdi.beloep" ,"balanse.anleggsmiddel.balanseverdiForAnleggsmiddel.skattemessigVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object sumGjeldOgEgenkapitalSkattemessigVerdi :  VerdifeltTypeSpecification<sumGjeldOgEgenkapitalSkattemessigVerdi>(gruppe= "balanse.sumGjeldOgEgenkapitalSkattemessigVerdi") {
    val erOverstyrt : FeltKoordinat<sumGjeldOgEgenkapitalSkattemessigVerdi> = FeltKoordinat("balanse.sumGjeldOgEgenkapitalSkattemessigVerdi.erOverstyrt")
    val beloep : FeltKoordinat<sumGjeldOgEgenkapitalSkattemessigVerdi> = FeltKoordinat("balanse.sumGjeldOgEgenkapitalSkattemessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object sumFinansinntekt :  VerdifeltTypeSpecification<sumFinansinntekt>(gruppe= "resultatregnskap.sumFinansinntekt") {
    val beloep : FeltKoordinat<sumFinansinntekt> = FeltKoordinat("resultatregnskap.sumFinansinntekt.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumFinansinntekt> = FeltKoordinat("resultatregnskap.sumFinansinntekt.erOverstyrt")
}
object varekostnader :  ForekomstTypeSpecification<varekostnader>("resultatregnskap.driftskostnad.varekostnader") {
    object varekostnad :  ForekomstTypeSpecification<varekostnad>("resultatregnskap.driftskostnad.varekostnader","resultatregnskap.driftskostnad.varekostnader.varekostnad") {
        val type : FeltKoordinat<varekostnad> = FeltKoordinat("resultatregnskap.driftskostnad.varekostnader.varekostnad.type")
        val beloep : FeltKoordinat<varekostnad> = FeltKoordinat("resultatregnskap.driftskostnad.varekostnader.varekostnad.beloep.beloep" ,"resultatregnskap.driftskostnad.varekostnader.varekostnad.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
}
object kortsiktigGjeld :  ForekomstTypeSpecification<kortsiktigGjeld>("balanse.gjeldOgEgenkapital.kortsiktigGjeld") {
    val overfoeresIkkeTilSkattemeldingen : FeltKoordinat<kortsiktigGjeld> = FeltKoordinat("balanse.gjeldOgEgenkapital.kortsiktigGjeld.overfoeresIkkeTilSkattemeldingen")
    val skattemessigVerdi : FeltKoordinat<kortsiktigGjeld> = FeltKoordinat("balanse.gjeldOgEgenkapital.kortsiktigGjeld.skattemessigVerdi.beloep" ,"balanse.gjeldOgEgenkapital.kortsiktigGjeld.skattemessigVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val kortsiktigGjeldtype : FeltKoordinat<kortsiktigGjeld> = FeltKoordinat("balanse.gjeldOgEgenkapital.kortsiktigGjeld.kortsiktigGjeldtype")
    val regnskapsmessigVerdi : FeltKoordinat<kortsiktigGjeld> = FeltKoordinat("balanse.gjeldOgEgenkapital.kortsiktigGjeld.regnskapsmessigVerdi.beloep" ,"balanse.gjeldOgEgenkapital.kortsiktigGjeld.regnskapsmessigVerdi", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object andreDriftskostnader :  ForekomstTypeSpecification<andreDriftskostnader>("resultatregnskap.driftskostnad.andreDriftskostnader") {
    object annenDriftskostnad :  ForekomstTypeSpecification<annenDriftskostnad>("resultatregnskap.driftskostnad.andreDriftskostnader","resultatregnskap.driftskostnad.andreDriftskostnader.annenDriftskostnad") {
        val type : FeltKoordinat<annenDriftskostnad> = FeltKoordinat("resultatregnskap.driftskostnad.andreDriftskostnader.annenDriftskostnad.type")
        val beloep : FeltKoordinat<annenDriftskostnad> = FeltKoordinat("resultatregnskap.driftskostnad.andreDriftskostnader.annenDriftskostnad.beloep.beloep" ,"resultatregnskap.driftskostnad.andreDriftskostnader.annenDriftskostnad.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    }
}
object samletGjeldOgFormuesobjekter :  ForekomstTypeSpecification<samletGjeldOgFormuesobjekter>("samletGjeldOgFormuesobjekter") {
    val verdiFoerVerdsettingsrabattForFormuesobjekterOmfattetAvVerdsettingsrabatt : FeltKoordinat<samletGjeldOgFormuesobjekter> = FeltKoordinat("samletGjeldOgFormuesobjekter.verdiFoerVerdsettingsrabattForFormuesobjekterOmfattetAvVerdsettingsrabatt.beloep" ,"samletGjeldOgFormuesobjekter.verdiFoerVerdsettingsrabattForFormuesobjekterOmfattetAvVerdsettingsrabatt", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val samletGjeld : FeltKoordinat<samletGjeldOgFormuesobjekter> = FeltKoordinat("samletGjeldOgFormuesobjekter.samletGjeld.beloep" ,"samletGjeldOgFormuesobjekter.samletGjeld", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val formuesverdiForFormuesobjekterIkkeOmfattetAvVerdsettingsrabatt : FeltKoordinat<samletGjeldOgFormuesobjekter> = FeltKoordinat("samletGjeldOgFormuesobjekter.formuesverdiForFormuesobjekterIkkeOmfattetAvVerdsettingsrabatt.beloep" ,"samletGjeldOgFormuesobjekter.formuesverdiForFormuesobjekterIkkeOmfattetAvVerdsettingsrabatt", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val verdiFoerVerdsettingsrabattForFormuesobjekterOmfattetAvVerdsettingsrabattTilordnetInnehaver : FeltKoordinat<samletGjeldOgFormuesobjekter> = FeltKoordinat("samletGjeldOgFormuesobjekter.verdiFoerVerdsettingsrabattForFormuesobjekterOmfattetAvVerdsettingsrabattTilordnetInnehaver.beloep" ,"samletGjeldOgFormuesobjekter.verdiFoerVerdsettingsrabattForFormuesobjekterOmfattetAvVerdsettingsrabattTilordnetInnehaver", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val samletGjeldTilordnetInnehaver : FeltKoordinat<samletGjeldOgFormuesobjekter> = FeltKoordinat("samletGjeldOgFormuesobjekter.samletGjeldTilordnetInnehaver.beloep" ,"samletGjeldOgFormuesobjekter.samletGjeldTilordnetInnehaver", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val formuesverdiForFormuesobjekterIkkeOmfattetAvVerdsettingsrabattTilordnetInnehaver : FeltKoordinat<samletGjeldOgFormuesobjekter> = FeltKoordinat("samletGjeldOgFormuesobjekter.formuesverdiForFormuesobjekterIkkeOmfattetAvVerdsettingsrabattTilordnetInnehaver.beloep" ,"samletGjeldOgFormuesobjekter.formuesverdiForFormuesobjekterIkkeOmfattetAvVerdsettingsrabattTilordnetInnehaver", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object sumKortsiktigGjeldSkattemessigVerdi :  VerdifeltTypeSpecification<sumKortsiktigGjeldSkattemessigVerdi>(gruppe= "balanse.gjeldOgEgenkapital.sumKortsiktigGjeldSkattemessigVerdi") {
    val erOverstyrt : FeltKoordinat<sumKortsiktigGjeldSkattemessigVerdi> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumKortsiktigGjeldSkattemessigVerdi.erOverstyrt")
    val beloep : FeltKoordinat<sumKortsiktigGjeldSkattemessigVerdi> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumKortsiktigGjeldSkattemessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object sumOmloepsmiddelRegnskapsmessigVerdi :  VerdifeltTypeSpecification<sumOmloepsmiddelRegnskapsmessigVerdi>(gruppe= "balanse.omloepsmiddel.sumOmloepsmiddelRegnskapsmessigVerdi") {
    val erOverstyrt : FeltKoordinat<sumOmloepsmiddelRegnskapsmessigVerdi> = FeltKoordinat("balanse.omloepsmiddel.sumOmloepsmiddelRegnskapsmessigVerdi.erOverstyrt")
    val beloep : FeltKoordinat<sumOmloepsmiddelRegnskapsmessigVerdi> = FeltKoordinat("balanse.omloepsmiddel.sumOmloepsmiddelRegnskapsmessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object sumLangsiktigGjeldRegnskapsmessigVerdi :  VerdifeltTypeSpecification<sumLangsiktigGjeldRegnskapsmessigVerdi>(gruppe= "balanse.gjeldOgEgenkapital.sumLangsiktigGjeldRegnskapsmessigVerdi") {
    val beloep : FeltKoordinat<sumLangsiktigGjeldRegnskapsmessigVerdi> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumLangsiktigGjeldRegnskapsmessigVerdi.beloep", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val erOverstyrt : FeltKoordinat<sumLangsiktigGjeldRegnskapsmessigVerdi> = FeltKoordinat("balanse.gjeldOgEgenkapital.sumLangsiktigGjeldRegnskapsmessigVerdi.erOverstyrt")
}
object transportmiddelINaering :  ForekomstTypeSpecification<transportmiddelINaering>("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering") {
    val registreringsaar : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.registreringsaar")
    val antallKilometerKjoertIAar : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.antallKilometerKjoertIAar")
    val erElektroniskKjoerebokFoertVedroerendeYrkeskjoering : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.erElektroniskKjoerebokFoertVedroerendeYrkeskjoering")
    val kjennemerke : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.kjennemerke")
    val biltype : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.biltype")
    val erYrkesbilenIBrukPrivat : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.erYrkesbilenIBrukPrivat")
    val tilbakefoertBilkostnadForPrivatBrukAvYrkesbil : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.tilbakefoertBilkostnadForPrivatBrukAvYrkesbil.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.tilbakefoertBilkostnadForPrivatBrukAvYrkesbil", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val leasingleie : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.leasingleie.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.leasingleie", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val antallMaanederTilDisposisjon : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.antallMaanederTilDisposisjon")
    val driftskostnader : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.driftskostnader.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.driftskostnader", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val antallKilometerYrkeskjoering : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.antallKilometerYrkeskjoering")
    val listeprisSomNy : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.listeprisSomNy.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.listeprisSomNy", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val saldoavskrivningPrivatBruk : FeltKoordinat<transportmiddelINaering> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.saldoavskrivningPrivatBruk.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.transportmiddelINaering.saldoavskrivningPrivatBruk", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
object virksomhet :  VerdifeltTypeSpecification<virksomhet>(gruppe= "virksomhet") {
    val regnskapspliktstype : FeltKoordinat<virksomhet> = FeltKoordinat("virksomhet.regnskapspliktstype")
    val selskapstype : FeltKoordinat<virksomhet> = FeltKoordinat("virksomhet.selskapstype")
    val antallMaanederDrevetIAar : FeltKoordinat<virksomhet> = FeltKoordinat("virksomhet.antallMaanederDrevetIAar")
}
object skattemessigVerdiPaaFordring :  ForekomstTypeSpecification<skattemessigVerdiPaaFordring>("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring") {
    val konstatertTapPaaKundefordring : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.konstatertTapPaaKundefordring.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.konstatertTapPaaKundefordring", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val annenFordring : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.annenFordring.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.annenFordring", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val kredittsalgIFjor : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.kredittsalgIFjor.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.kredittsalgIFjor", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val konstatertTapPaaKundefordringIFjor : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.konstatertTapPaaKundefordringIFjor.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.konstatertTapPaaKundefordringIFjor", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val sumSkattemessigVerdiPaaFordring : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.sumSkattemessigVerdiPaaFordring.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.sumSkattemessigVerdiPaaFordring", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val kredittsalg : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.kredittsalg.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.kredittsalg", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val skattemessigNedskrivningPaaKundefordring : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.skattemessigNedskrivningPaaKundefordring.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.skattemessigNedskrivningPaaKundefordring", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val kundefordringOgIkkeFakturertDriftsinntekt : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.kundefordringOgIkkeFakturertDriftsinntekt.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.kundefordringOgIkkeFakturertDriftsinntekt", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val skattemessigNedskrivningPaaKundefordringForNyetablertVirksomhet : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.skattemessigNedskrivningPaaKundefordringForNyetablertVirksomhet.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.skattemessigNedskrivningPaaKundefordringForNyetablertVirksomhet", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
    val skattemessigVerdiPaaKundefordring : FeltKoordinat<skattemessigVerdiPaaFordring> = FeltKoordinat("spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.skattemessigVerdiPaaKundefordring.beloep" ,"spesifikasjonAvResultatregnskapOgBalanse.skattemessigVerdiPaaFordring.skattemessigVerdiPaaKundefordring", dataType = FieldDataType(FieldDataType.ActualType.DecimalType, 2))
}
